# version: "3"
networks:
  application:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ta-booking-system
    ports:
      - "8003:8000"
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_DATABASE=ta_booking_system_db
      - DB_USERNAME=ta_booking_system_user
      - DB_PASSWORD=ta_booking_system_password
    networks:
      - application
    env_file: 
      - .env
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        composer install
        php artisan migrate
        npm install
        npm run dev & 
        php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"  # Ubah dari 3306:3306 menjadi 3307:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ta_booking_system_db
      - MYSQL_USER=ta_booking_system_user      # Jangan gunakan 'root' sebagai username
      - MYSQL_PASSWORD=ta_booking_system_password
    networks:
      - application
    container_name: ta-booking-system-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ta-booking-system-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - application
    depends_on:
      - db