name: Build and deploy Laravel to Production VPS - link2pay
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install NPM Dependencies
      run: npm install

    - name: Build NPM Assets
      run: npm run build
      env:
        VITE_APP_URL: ${{ secrets.APP_URL }}
        VITE_APP_NAME: "Link2Pay"
        APP_URL: ${{ secrets.APP_URL }}
        APP_NAME: "Link2Pay"

    - name: Zip artifact for deployment
      run: zip -r release.zip . -x ".env" ".git/*" "node_modules/*" "tests/*" "storage/logs/*" ".github/*" "diagram.drawio" "README.md" "prettier.config.js" "pint.json" ".editorconfig"

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: laravel-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: laravel-app

    - name: Unzip artifact
      run: unzip -o release.zip

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Create backup of current deployment
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          if [ -d '/var/www/html/link2pay' ]; then
            rm -rf /var/www/html/link2pay_backup 2>/dev/null || true
            cp -r /var/www/html/link2pay /var/www/html/link2pay_backup 2>/dev/null || true
          fi
          mkdir -p /var/www/html/link2pay
        "

    - name: Deploy files to VPS (rsync)
      run: |
        rsync -rlDvz --delete \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='tests' \
          --exclude='storage' \
          --exclude='.env' \
          ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/html/link2pay/

    - name: Run Laravel setup commands on VPS
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd /var/www/html/link2pay
          
          # Delete zip file
          rm -f release.zip

          # Run migrations
          php artisan migrate --force

          # Run Laravel optimizations
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Link storage
          php artisan storage:link
        "

    - name: Cleanup SSH key & zip file
      if: always()
      run: |
        rm -f ~/.ssh/deploy_key